config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :wishlist_items
    resources :list_shares
  end

  # resources :wishlist_items
  resource :session, only: [ :new, :create, :destroy ]
  resource :registration, only: [ :new, :create ]

  resources :email_address_verifications, only: [ :show ], param: :token do
    collection do
      post "resend"
    end
  end

  get "/unverified" => "email_address_verifications#unverified", as: :unverified

  resources :passwords, param: :token

  get "/shared/:share_token", to: "shared#shared"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "homepage#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/list.rb
class List < ApplicationRecord
  include UserAttributable
  has_many :wishlist_items, dependent: :destroy
  has_many :list_shares, dependent: :destroy
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = policy_scope(List)
  end

  # GET /lists/1 or /lists/1.json
  def show
    authorize @list
    respond_to do |format|
      format.html { redirect_to list_wishlist_items_path(@list) }
    end
  end

  # GET /lists/new
  def new
    authorize List

    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    authorize @list
  end

  # POST /lists or /lists.json
  def create
    authorize List

    @list = List.new(**list_params, user_id: Current.user.id)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    authorize @list

    @list.destroy!

    respond_to do |format|
      format.html { redirect_to lists_path, status: :see_other, notice: "List was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.expect(list: [ :wishlist_items_id, :title, :description ])
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, class: "contents") do |form| %>
  <div class="pt-8">
    <h3 class="text-lg font-bold">Create new list</h3>
    <% if list.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

        <ul>
          <% list.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5 flex flex-col gap-y-2 lg:grid lg:grid-cols-5 lg:gap-y-4 lg:items-center">
      <%= form.label :title, "Title:", class: "font-medium col-span-1" %>
      <%= form.text_field :title, placeholder: 'Title', class: "text-input col-span-4" %>

      <%= form.label :description, "Description:", class: "font-medium col-span-1 mt-2 lg:mt-0" %>
      <%= form.text_field :description, placeholder: 'Description', class: "text-input col-span-4" %>
    </div>

    <div class="inline">
      <%= form.submit class: "button-success" %>
    </div>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="bg-white rounded-lg shadow hover:shadow-lg transition-shadow p-6 dark:bg-slate-800">
  <%= link_to list_path(list), class: "block" do %>
    <h2 class="text-xl font-semibold text-slate-900 dark:text-slate-50"><%= list.title %></h2>
    <h3 class="text-m text-slate-900 dark:text-slate-50"><%= list.description %></h2>
    <p class="text-slate-600 mt-2 dark:text-slate-400"><%= pluralize(list.wishlist_items.count, 'item') %></p>
    <p class="text-sm text-slate-400 mt-8">
      Last updated: <%= time_ago_in_words(list.updated_at) %> ago
    </p>
  <% end %>
</div>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.append "lists", @list %>
<%= turbo_stream.replace 'new_list', partial: 'form', locals: { list: List.new } %>

app/views/lists/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing list</h1>

  <%= render "form", list: @list %>

  <%= link_to "Discard changes", @list, class: "button-default" %>
</div>

app/views/lists/index.html.erb
<div class="w-full">
  <% content_for :title, "Lists" %>
  <h1 class="font-bold text-4xl mb-8">Lists</h1>

  <div id="lists" class="min-w-full flex flex-col gap-4">
    <% @lists.each do |list| %>
      <%= render list %>
    <% end %>
  </div>

  <%= turbo_frame_tag id="new_list", src:new_list_path %>
</div>

app/views/lists/new.html.erb
<%= turbo_frame_tag id="new_list" do %>
  <%= render "form", list: @list %>
<% end %>

app/views/lists/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-500-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>


    <div id="<%= dom_id @list %>">
      <p class="my-5">
      <strong class="block font-medium mb-1">Title:</strong>
      <%= @list.title %>
      </p>

      <p class="my-5">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= @list.description %>
      </p>

      <p class="my-5">
      <strong class="block font-medium mb-1">Number of items:</strong>
      <%= @list.wishlist_items.count %>
      </p>
    </div>

    <div id="list_items">
      <ul>
        <% @list.wishlist_items.each do |item| %>
          <li>
            <strong><%= item.title %></strong>
            <strong><%= item.description %></strong>
            <a href=<%=item.url %>><%= item.url %></a>
          </li>
        <% end %>
      </ul>
    </div>

    <%= link_to 'Add item', list_wishlist_items_path(@list), class: "button-success" %>
    <%= link_to "Edit this list", edit_list_path(@list), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to lists", lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>