config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :wishlist_items
    resources :list_shares
  end

  # resources :wishlist_items
  resource :session, only: [ :new, :create, :destroy ]
  resource :registration, only: [ :new, :create ]

  resources :email_address_verifications, only: [ :show ], param: :token do
    collection do
      post "resend"
    end
  end

  get "/unverified" => "email_address_verifications#unverified", as: :unverified

  resources :passwords, param: :token

  get "/shared/:share_token", to: "shared#shared"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "homepage#index"

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
  include UserAttributable
  belongs_to :list
end

app/controllers/wishlist_items_controller.rb
class WishlistItemsController < ApplicationController
  before_action :get_list
  before_action :set_wishlist_item, only: %i[ show edit update destroy ]

  # GET /wishlist_items or /wishlist_items.json
  def index
    @wishlist_items = policy_scope(@list.wishlist_items.order(created_at: :desc))
  end

  # GET /wishlist_items/1 or /wishlist_items/1.json
  def show
    authorize @wishlist_item
  end

  # GET /wishlist_items/new
  def new
    authorize WishlistItem

    @wishlist_item = @list.wishlist_items.build
  end

  # GET /wishlist_items/1/edit
  def edit
    authorize @wishlist_item
  end

  # POST /wishlist_items or /wishlist_items.json
  def create
    authorize WishlistItem

    begin
      preview = LinkThumbnailer.generate(wishlist_item_params[:url])
      @wishlist_item = @list.wishlist_items.build(url: wishlist_item_params[:url], title: preview.title, description: preview.description)
      raise LinkThumbnailer::Exceptions
    rescue LinkThumbnailer::Exceptions => e
      Sentry.capture_exception(e)
      @wishlist_item = @list.wishlist_items.build(url: wishlist_item_params[:url], title: wishlist_item_params[:url])
      flash[:alert] = "Couldn't fetch details from the URL. Please fill in the details manually."
    end

    respond_to do |format|
      if @wishlist_item.save
        format.html { redirect_to list_wishlist_items_path, notice: "Wishlist item was successfully created." }
        format.json { render :show, status: :created, location: @wishlist_item }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wishlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlist_items/1 or /wishlist_items/1.json
  def update
    authorize @wishlist_item

    respond_to do |format|
      if @wishlist_item.update(wishlist_item_params)
        format.html { redirect_to list_wishlist_items_path(@list), notice: "Wishlist item was successfully updated." }
        format.json { render :show, status: :ok, location: @wishlist_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wishlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlist_items/1 or /wishlist_items/1.json
  def destroy
    authorize @wishlist_item
    @wishlist_item.destroy!

    respond_to do |format|
      format.html { redirect_to list_wishlist_items_path(@list), status: :see_other, notice: "Wishlist item was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist_item
      @wishlist_item = @list.wishlist_items.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def wishlist_item_params
      params.expect(wishlist_item: [ :url, :title, :description ])
    end

    def get_list
      @list = List.find(params[:list_id])
    end
end

app/helpers/wishlist_items_helper.rb
module WishlistItemsHelper
end

app/views/wishlist_items/_create_form.html.erb
<%= form_for [@list, wishlist_item] do |form| %>
  <% if wishlist_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(wishlist_item.errors.count, "error") %> prohibited this wishlist_item from being saved:</h2>

      <ul>
        <% wishlist_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex gap-2 items-center flex-wrap flex-col w-full md:flex-row md:flex-nowrap py-8">
    <div class="w-full md:w-fit">
      <%= form.text_field :url, placeholder: "URL", class: "text-input" %>
    </div>

    <%= form.submit "Add item", data: {turbo_submits_with: "Fetching info..."}, class: "button-success w-full md:w-fit" %>
  </div>
<% end %>

app/views/wishlist_items/_form.html.erb
<%= form_for [@list, wishlist_item] do |form| %>
  <% if wishlist_item.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(wishlist_item.errors.count, "error") %> prohibited this wishlist_item from being saved:</h2>

      <ul>
        <% wishlist_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex gap-2 items-center flex-wrap flex-col w-full py-8">
    <div class="w-full">
      <%= form.text_field :url, placeholder: "URL", class: "text-input" %>
    </div>

    <div class="w-full">
      <%= form.text_field :title, placeholder: "Title", class: "text-input" %>
    </div>

    <div class="w-full">
      <%= form.text_area :description, placeholder: "Description", class: "text-input", rows: 7 %>
    </div>

    <div class="w-full flex gap-2">
      <%= link_to "Back to list", list_wishlist_items_path(@list), class: "button-default"  %>
      <%= form.submit "Update", class: "button-success" %>
    </div>
  </div>
<% end %>

app/views/wishlist_items/_wishlist_item.html.erb
<div id="<%= dom_id wishlist_item %>">
  <div class="p-6 bg-white border border-gray-500-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-500-700 flex flex-col gap-2">
    <h5 class="text-2xl font-bold tracking-tight dark:text-white">
      <%= wishlist_item.title %>
    </h5>
    <p class="font-normal">
    <%= wishlist_item.description %>
    </p>

    <div class="flex gap-2 flex-col md:flex-row">
      <a target="_blank" href="<%= wishlist_item.url %>"  class="button-primary button--full-width">
        Visit link
      </a>
      <%= link_to "Edit item" , edit_list_wishlist_item_path(@list, wishlist_item), class: "button-default button--full-width" %>
      <%= button_to "Delete item", list_wishlist_item_path(@list, wishlist_item), method: :delete, form: {data: {turbo_confirm: "Delete item #{wishlist_item.title}?"}}, class: "button-danger button--full-width"  %>
    </div>
  </div>
</div>

app/views/wishlist_items/create.turbo_stream.erb
<%= turbo_stream.prepend "wishlist_items", @wishlist_item %>
<%= turbo_stream.replace 'new_list_wishlist_item', partial: 'create_form', locals: { wishlist_item: @list.wishlist_items.new } %>
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/wishlist_items/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing wishlist item</h1>

  <div class="container">
    <%= render "form", wishlist_item: @wishlist_item %>
  </div

</div>

app/views/wishlist_items/index.html.erb
<% content_for :header_actions do %>
  <%= link_to list_list_shares_path, 
    class: "inline-flex items-center px-4 py-2 rounded-full bg-indigo-500 text-white hover:bg-indigo-600 transition-colors" do %>
    <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                                                           d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z"/>
    </svg>
    Share
  <% end %>
<% end %>

<%= render "shared/nav", title: @list.title %>
<main class="max-w-7xl mx-auto px-4 py-8">
  <div class="space-y-4">
    <div class="flex justify-between items-center">
      <%= turbo_frame_tag id="new_list_wishlist_item", src:new_list_wishlist_item_path(list: @list.id), class: "w-full" %>
    </div>
    <div id="wishlist_items">
      <% @wishlist_items.each do |wishlist_item| %>
        <%= render wishlist_item %>
      <% end %>
    </div>
  </div>
</main>

app/views/wishlist_items/new.html.erb
<%= turbo_frame_tag id="new_list_wishlist_item", class: "w-full" do %>
  <div class="mx-auto w-full">
    <%= render "create_form", wishlist_item: @wishlist_item %>
  </div>
<% end %>

app/views/wishlist_items/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-500-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @wishlist_item %>

    <%= link_to "Edit this wishlist item", edit_list_wishlist_item_path(@list, @wishlist_item), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this wishlist item", list_wishlist_item_path(@list, @wishlist_item), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>